import { StepActionType } from '@bio/database';
import { PathwayTemplate } from '../interfaces/pathway-template.interface.js';

export const PATHWAY_TEMPLATES: PathwayTemplate[] = [
  {
    templateId: 'HYPERTENSION_UNCONTROLLED',
    name: 'Jornada — Hipertensão Arterial Não Controlada',
    description: 'Fluxo estruturado de acompanhamento para pacientes com hipertensão fora da meta terapêutica.',
    clinicalCode: 'I10',
    priority: 'HIGH',
    steps: [
      {
        sequence: 1,
        title: 'Avaliação Cardiovascular Inicial',
        description: 'Anamnese dirigida, exame físico com ausculta cardíaca e pulmonar, cálculo do risco cardiovascular global (Framingham/Escore Brasil).',
        actionType: StepActionType.ASSESSMENT,
        dueDaysFromStart: 0,
      },
      {
        sequence: 2,
        title: 'Solicitar Exames Laboratoriais',
        description: 'Hemograma, glicemia de jejum, creatinina, ureia, potássio, sódio, perfil lipídico, ácido úrico, EAS, microalbuminúria e ECG de 12 derivações.',
        actionType: StepActionType.LABORATORY,
        dueDaysFromStart: 3,
      },
      {
        sequence: 3,
        title: 'Revisão ou Início de Anti-Hipertensivo',
        description: 'Avaliar esquema atual. Considerar intensificação para monoterapia em dose máxima ou combinação de classes (IECA/BRA + diurético tiazídico ou bloqueador de canal de cálcio).',
        actionType: StepActionType.MEDICATION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 4,
        title: 'Orientação sobre Estilo de Vida',
        description: 'Redução de sódio (< 2 g/dia), dieta DASH, cessação tabágica, redução do consumo de álcool, manejo do estresse e sono adequado.',
        actionType: StepActionType.LIFESTYLE,
        dueDaysFromStart: 7,
      },
      {
        sequence: 5,
        title: 'Reavaliação em 30 Dias',
        description: 'Verificar adesão ao tratamento, medir PA em ambos os braços, revisar exames solicitados e ajustar conduta conforme resposta terapêutica.',
        actionType: StepActionType.FOLLOW_UP,
        dueDaysFromStart: 30,
      },
    ],
  },
  {
    templateId: 'DIABETES_HIGH_RISK',
    name: 'Jornada — Diabetes Mellitus com Controle Inadequado',
    description: 'Fluxo de acompanhamento para pacientes com DM2 e controle glicêmico insatisfatório (glicemia ≥ 180 ou HbA1c ≥ 8%).',
    clinicalCode: 'E11',
    priority: 'HIGH',
    steps: [
      {
        sequence: 1,
        title: 'Avaliação Clínica do Controle Glicêmico',
        description: 'Revisar frequência de hipoglicemias, adesão ao tratamento, técnica de aplicação de insulina (se houver), complicações micro e macrovasculares.',
        actionType: StepActionType.ASSESSMENT,
        dueDaysFromStart: 0,
      },
      {
        sequence: 2,
        title: 'Solicitar Painel Laboratorial Completo',
        description: 'HbA1c, glicemia de jejum e pós-prandial, perfil lipídico, creatinina, microalbuminúria, TGO/TGP, TSH, urina tipo 1.',
        actionType: StepActionType.LABORATORY,
        dueDaysFromStart: 3,
      },
      {
        sequence: 3,
        title: 'Revisão do Esquema Terapêutico',
        description: 'Avaliar necessidade de intensificação: incremento de dose, troca de classe (SGLT2i, GLP-1 RA, DPP-4i) ou introdução/ajuste de insulina.',
        actionType: StepActionType.MEDICATION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 4,
        title: 'Orientação Nutricional Individualizada',
        description: 'Plano alimentar com restrição de carboidratos de alto índice glicêmico, fracionamento das refeições (5-6/dia), controle de porções e hidratação.',
        actionType: StepActionType.NUTRITION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 5,
        title: 'Monitoramento e Controle em 60 Dias',
        description: 'Nova HbA1c, glicemia de jejum, peso, PA e revisão de complicações. Ajuste terapêutico conforme resposta.',
        actionType: StepActionType.FOLLOW_UP,
        dueDaysFromStart: 60,
      },
    ],
  },
  {
    templateId: 'SEVERE_OBESITY',
    name: 'Jornada — Obesidade Grave (IMC ≥ 35)',
    description: 'Fluxo multidisciplinar para pacientes com obesidade grau II com comorbidades ou obesidade grau III.',
    clinicalCode: 'E66',
    priority: 'HIGH',
    steps: [
      {
        sequence: 1,
        title: 'Avaliação Multidisciplinar Inicial',
        description: 'Anamnese completa com histórico de tentativas de perda de peso, avaliação de comorbidades, composição corporal (bioimpedância), rastreamento de apneia do sono.',
        actionType: StepActionType.ASSESSMENT,
        dueDaysFromStart: 0,
      },
      {
        sequence: 2,
        title: 'Exames Metabólicos Completos',
        description: 'Glicemia de jejum, insulina basal, HOMA-IR, HbA1c, perfil lipídico, TSH, T4 livre, cortisol, perfil hepático (AST/ALT/GGT), vitamina D e B12.',
        actionType: StepActionType.LABORATORY,
        dueDaysFromStart: 3,
      },
      {
        sequence: 3,
        title: 'Plano Alimentar Individualizado',
        description: 'Déficit calórico de 500-750 kcal/dia. Dieta hiperproteica (> 1,2 g/kg/dia). Avaliação de indicação de very low calorie diet (VLCD) se IMC ≥ 40.',
        actionType: StepActionType.NUTRITION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 4,
        title: 'Prescrição de Exercício Supervisionado',
        description: 'Iniciar com atividade de baixo impacto (hidroginástica, caminhada em esteira). Progredir para 150-300 min/semana de atividade moderada. Avaliar indicação de treinamento resistido.',
        actionType: StepActionType.EXERCISE,
        dueDaysFromStart: 14,
      },
      {
        sequence: 5,
        title: 'Reavaliação e Decisão Cirúrgica em 60 Dias',
        description: 'Avaliar perda de peso alcançada (meta: ≥ 5%). Discutir indicação de cirurgia bariátrica se IMC ≥ 40 ou ≥ 35 com comorbidades não controladas.',
        actionType: StepActionType.FOLLOW_UP,
        dueDaysFromStart: 60,
      },
    ],
  },
  {
    templateId: 'DYSLIPIDEMIA_SIGNIFICANT',
    name: 'Jornada — Dislipidemia Importante',
    description: 'Fluxo de acompanhamento para pacientes com LDL ≥ 190 mg/dL ou triglicerídeos ≥ 500 mg/dL.',
    clinicalCode: 'E78',
    priority: 'HIGH',
    steps: [
      {
        sequence: 1,
        title: 'Cálculo do Risco Cardiovascular',
        description: 'Estratificação de risco pelo Escore de Risco Brasil ou Framingham. Investigar hipercolesterolemia familiar (critérios Dutch Lipid Clinic Network). Avaliar causas secundárias (hipotireoidismo, síndrome nefrótica, DM2).',
        actionType: StepActionType.ASSESSMENT,
        dueDaysFromStart: 0,
      },
      {
        sequence: 2,
        title: 'Painel Lipídico Completo e Função Hepática',
        description: 'Colesterol total, LDL, HDL, VLDL, triglicerídeos, não-HDL, LDL oxidado (se disponível). TGO, TGP, GGT, TSH e glicemia de jejum para excluir causas secundárias.',
        actionType: StepActionType.LABORATORY,
        dueDaysFromStart: 3,
      },
      {
        sequence: 3,
        title: 'Iniciar ou Ajustar Terapia Hipolipemiante',
        description: 'Para LDL ≥ 190: estatina de alta potência (rosuvastatina 20-40 mg ou atorvastatina 40-80 mg). Para TG ≥ 500: fibratos + restrição de gordura e álcool. Considerar ezetimiba ou inibidores PCSK9 em alto risco.',
        actionType: StepActionType.MEDICATION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 4,
        title: 'Orientação sobre Dieta Hipolipemiante',
        description: 'Reduzir gordura saturada (< 7% VCT), eliminar gordura trans, aumentar fibras solúveis (aveia, legumes), ômega-3 (se TG elevado), consumo de fitoesteróis.',
        actionType: StepActionType.NUTRITION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 5,
        title: 'Controle Lipídico em 90 Dias',
        description: 'Novo perfil lipídico. Meta: LDL < 70 mg/dL (alto risco) ou LDL < 50 mg/dL (muito alto risco). Avaliar TGO/TGP para monitoramento de hepatotoxicidade da estatina.',
        actionType: StepActionType.FOLLOW_UP,
        dueDaysFromStart: 90,
      },
    ],
  },
  {
    templateId: 'METABOLIC_SYNDROME',
    name: 'Jornada — Síndrome Metabólica',
    description: 'Fluxo de intervenção intensiva para regressão da síndrome metabólica e prevenção de DM2 e DCV.',
    clinicalCode: 'E88.8',
    priority: 'MEDIUM',
    steps: [
      {
        sequence: 1,
        title: 'Avaliação Completa da Síndrome Metabólica',
        description: 'Confirmar todos os critérios presentes. Medir circunferência abdominal, PA, glicemia, triglicerídeos e HDL. Estratificar risco cardiovascular e de DM2 a 10 anos.',
        actionType: StepActionType.ASSESSMENT,
        dueDaysFromStart: 0,
      },
      {
        sequence: 2,
        title: 'Painel Laboratorial Metabólico',
        description: 'Glicemia de jejum e 2h pós-75 g de glicose (TOTG), insulina basal, HOMA-IR, HbA1c, perfil lipídico completo, PCR ultrassensível, ácido úrico, ácido graxo livre.',
        actionType: StepActionType.LABORATORY,
        dueDaysFromStart: 3,
      },
      {
        sequence: 3,
        title: 'Intervenção Intensiva em Estilo de Vida',
        description: 'Meta: redução de 5-10% do peso corporal. Counseling motivacional. Cessação tabágica. Redução do consumo de álcool. Melhora da qualidade do sono (meta: 7-9h/noite).',
        actionType: StepActionType.LIFESTYLE,
        dueDaysFromStart: 7,
      },
      {
        sequence: 4,
        title: 'Dieta Mediterrânea ou DASH',
        description: 'Alto teor de fibras, vegetais, frutas, grãos integrais, azeite de oliva, peixes e nozes. Restrição de açúcares simples, processados e carnes vermelhas. Controle de sódio (< 2 g/dia).',
        actionType: StepActionType.NUTRITION,
        dueDaysFromStart: 7,
      },
      {
        sequence: 5,
        title: 'Programa de Atividade Física',
        description: '≥ 150 min/semana de atividade aeróbica de intensidade moderada (caminhada rápida, bicicleta, natação). Adicionar 2-3 sessões/semana de treino resistido. Reduzir tempo sedentário.',
        actionType: StepActionType.EXERCISE,
        dueDaysFromStart: 14,
      },
      {
        sequence: 6,
        title: 'Reavaliação dos Critérios em 90 Dias',
        description: 'Repetir avaliação de todos os critérios da síndrome metabólica. Nova glicemia de jejum, HOMA-IR, perfil lipídico, PA e circunferência abdominal. Avaliar regressão da síndrome.',
        actionType: StepActionType.FOLLOW_UP,
        dueDaysFromStart: 90,
      },
    ],
  },
];

export function findTemplate(templateId: string): PathwayTemplate | undefined {
  return PATHWAY_TEMPLATES.find((t) => t.templateId === templateId);
}
