import { ClinicalGuideline } from '../entities/clinical-guideline.entity.js';

export const BUILT_IN_GUIDELINES: ClinicalGuideline[] = [
  new ClinicalGuideline({
    id: 'gl-sbc-2020',
    title: 'Diretrizes Brasileiras de Hipertensão Arterial',
    organization: 'Sociedade Brasileira de Cardiologia (SBC)',
    version: '2020',
    publishedAt: '2020-01-01',
    url: 'https://www.scielo.br/j/abc/a/wppMBGwrMf4tBDzBnDFJGsB/',
    tags: ['hipertensão', 'pressão arterial', 'cardiovascular', 'cardiologia'],
    metadata: { language: 'pt-BR', country: 'Brasil', icdCodes: ['I10', 'I11', 'I12', 'I13'] },
  }),
  new ClinicalGuideline({
    id: 'gl-sbd-2022',
    title: 'Diretriz da Sociedade Brasileira de Diabetes',
    organization: 'Sociedade Brasileira de Diabetes (SBD)',
    version: '2022-2023',
    publishedAt: '2022-06-01',
    url: 'https://diretriz.diabetes.org.br/',
    tags: ['diabetes', 'glicemia', 'insulina', 'HbA1c', 'endocrinologia'],
    metadata: { language: 'pt-BR', country: 'Brasil', icdCodes: ['E10', 'E11', 'E12', 'E13'] },
  }),
  new ClinicalGuideline({
    id: 'gl-sbdc-2017',
    title: 'Diretriz Brasileira de Dislipidemia e Prevenção da Aterosclerose',
    organization: 'Sociedade Brasileira de Cardiologia (SBC)',
    version: '2017',
    publishedAt: '2017-04-01',
    url: 'https://www.scielo.br/j/abc/a/9ck4bkpkckFBnQMkN5vPhHL/',
    tags: ['dislipidemia', 'colesterol', 'LDL', 'HDL', 'triglicerídeos', 'aterosclerose'],
    metadata: { language: 'pt-BR', country: 'Brasil', icdCodes: ['E78'] },
  }),
  new ClinicalGuideline({
    id: 'gl-who-pa-2020',
    title: 'WHO Guidelines on Physical Activity and Sedentary Behaviour',
    organization: 'World Health Organization (WHO)',
    version: '2020',
    publishedAt: '2020-11-25',
    url: 'https://www.who.int/publications/i/item/9789240015128',
    tags: ['atividade física', 'exercício', 'sedentarismo', 'saúde pública'],
    metadata: { language: 'en', country: 'Global', icdCodes: ['Z72.3'] },
  }),
  new ClinicalGuideline({
    id: 'gl-ada-2024',
    title: 'Standards of Medical Care in Diabetes',
    organization: 'American Diabetes Association (ADA)',
    version: '2024',
    publishedAt: '2024-01-01',
    url: 'https://diabetesjournals.org/care/issue/47/Supplement_1',
    tags: ['diabetes', 'cuidados clínicos', 'glicemia', 'HbA1c', 'endocrinologia'],
    metadata: { language: 'en', country: 'USA', icdCodes: ['E10', 'E11'] },
  }),
  new ClinicalGuideline({
    id: 'gl-ms-guia-2014',
    title: 'Guia Alimentar para a População Brasileira',
    organization: 'Ministério da Saúde do Brasil',
    version: '2014',
    publishedAt: '2014-11-01',
    url: 'https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_populacao_brasileira_2ed.pdf',
    tags: ['nutrição', 'alimentação', 'dieta', 'ultra-processados', 'saúde pública'],
    metadata: { language: 'pt-BR', country: 'Brasil' },
  }),
  new ClinicalGuideline({
    id: 'gl-esc-2021-cv-prevention',
    title: 'ESC Guidelines on Cardiovascular Disease Prevention in Clinical Practice',
    organization: 'European Society of Cardiology (ESC)',
    version: '2021',
    publishedAt: '2021-09-01',
    url: 'https://academic.oup.com/eurheartj/article/42/34/3227/6358713',
    tags: ['prevenção cardiovascular', 'cardiologia', 'risco cardiovascular', 'estilo de vida'],
    metadata: { language: 'en', country: 'Europa' },
  }),
  new ClinicalGuideline({
    id: 'gl-aasm-2023',
    title: 'Clinical Practice Guideline for Diagnostic Testing for Adult Obstructive Sleep Apnea',
    organization: 'American Academy of Sleep Medicine (AASM)',
    version: '2023',
    publishedAt: '2023-05-01',
    url: 'https://jcsm.aasm.org/',
    tags: ['sono', 'apneia do sono', 'insônia', 'diagnóstico'],
    metadata: { language: 'en', country: 'USA', icdCodes: ['G47.33'] },
  }),
];
