import { ClinicalReference } from '../entities/clinical-reference.entity.js';

export const BUILT_IN_REFERENCES: ClinicalReference[] = [
  new ClinicalReference({
    id: 'ref-001',
    title: 'Effect of Dietary Sodium Reduction on Blood Pressure',
    description: 'Meta-análise de 133 estudos randomizados demonstrando redução média de 5,4 mmHg sistólica e 2,8 mmHg diastólica com redução de sódio para < 2g/dia.',
    tags: ['hipertensão', 'sódio', 'pressão arterial', 'cardiologia', 'meta-análise'],
    confidence: 0.95,
    language: 'en',
  }),
  new ClinicalReference({
    id: 'ref-002',
    title: 'Metformina na Prevenção do Diabetes Tipo 2',
    description: 'Diabetes Prevention Program (DPP): metformina reduziu incidência de DM2 em 31% vs placebo; intervenção intensiva no estilo de vida reduziu 58% — ambos em indivíduos de alto risco.',
    tags: ['diabetes', 'metformina', 'prevenção', 'pré-diabetes', 'endocrinologia'],
    confidence: 0.95,
    language: 'pt-BR',
  }),
  new ClinicalReference({
    id: 'ref-003',
    title: 'Exercício Físico e Mortalidade Cardiovascular',
    description: 'Coorte prospectiva com 122.007 participantes (Mandsager et al., JAMA 2018): capacidade cardiorrespiratória é o preditor mais forte de mortalidade por todas as causas, superando tabagismo, hipertensão e diabetes.',
    tags: ['exercício', 'mortalidade cardiovascular', 'VO2max', 'condicionamento', 'prognóstico'],
    confidence: 0.92,
    language: 'pt-BR',
  }),
  new ClinicalReference({
    id: 'ref-004',
    title: 'Sleep Duration and Cardiovascular Risk',
    description: 'Meta-análise (He et al., JAHA 2023): sono < 6h/noite associado a HR 1,35 para eventos cardiovasculares maiores (MACE). Sono > 9h também associado a risco aumentado (curva em U).',
    tags: ['sono', 'risco cardiovascular', 'duração do sono', 'cardiologia', 'epidemiologia'],
    confidence: 0.88,
    language: 'en',
  }),
  new ClinicalReference({
    id: 'ref-005',
    title: 'Mediterranean Diet and Longevity — PREDIMED Trial',
    description: 'PREDIMED (NEJM 2013): dieta mediterrânea suplementada com azeite extravirgem ou nozes reduziu eventos cardiovasculares maiores em 30% (HR 0,70) versus dieta controle em ~7.500 participantes.',
    tags: ['dieta mediterrânea', 'longevidade', 'cardiologia', 'nutrição', 'prevenção cardiovascular'],
    confidence: 0.93,
    language: 'en',
  }),
  new ClinicalReference({
    id: 'ref-006',
    title: 'Telomere Length and Biological Aging',
    description: 'Revisão (Blackburn & Epel, Nature 2017): comprimento dos telômeros é biomarcador de envelhecimento biológico; estilo de vida saudável (exercício, sono, meditação) preserva telômeros via ativação da telomerase.',
    tags: ['telômeros', 'longevidade', 'envelhecimento biológico', 'estresse oxidativo', 'telomerase'],
    confidence: 0.80,
    language: 'en',
  }),
  new ClinicalReference({
    id: 'ref-007',
    title: 'Síndrome Metabólica: Prevalência e Impacto no Brasil',
    description: 'ELSA-Brasil: prevalência de síndrome metabólica de 44,9% na população adulta brasileira; associação forte com sedentarismo, obesidade abdominal e dieta ocidentalizada.',
    tags: ['síndrome metabólica', 'Brasil', 'prevalência', 'metabolismo', 'ELSA-Brasil'],
    confidence: 0.90,
    language: 'pt-BR',
  }),
  new ClinicalReference({
    id: 'ref-008',
    title: 'High-Sensitivity CRP as Cardiovascular Risk Marker',
    description: 'Jupiter Trial (NEJM 2008): PCR-us ≥ 2 mg/L em indivíduos com LDL < 130 mg/dL beneficiam-se de rosuvastatina (redução 44% MACE, 20% mortalidade geral).',
    tags: ['PCR', 'inflamação', 'risco cardiovascular', 'estatina', 'biomarcadores'],
    confidence: 0.91,
    language: 'en',
  }),
  new ClinicalReference({
    id: 'ref-009',
    title: 'Cognitive Behavioral Therapy for Insomnia (CBT-I)',
    description: 'Revisão Cochrane 2020: CBT-I superior a farmacoterapia em longo prazo para insônia crônica — redução do tempo de latência do sono (−19 min) e aumento da eficiência do sono (+9,9%).',
    tags: ['insônia', 'TCC', 'sono', 'psicoterapia', 'saúde mental', 'Cochrane'],
    confidence: 0.95,
    language: 'pt-BR',
  }),
  new ClinicalReference({
    id: 'ref-010',
    title: 'Polypharmacy in the Elderly — Beers Criteria 2023',
    description: 'AGS Beers Criteria 2023: lista de 60+ medicamentos ou classes potencialmente inapropriados em idosos ≥ 65 anos; uso associado a quedas, hospitalização e mortalidade aumentada.',
    tags: ['geriatria', 'polifarmácia', 'idoso', 'Beers', 'medicamentos', 'segurança do paciente'],
    confidence: 0.95,
    language: 'pt-BR',
  }),
];
