import { ClinicalRule } from '../entities/clinical-rule.entity.js';

export const BUILT_IN_RULES: ClinicalRule[] = [
  new ClinicalRule({
    id: 'rule-card-001',
    category: 'CARDIOLOGY',
    condition: 'Pressão arterial ≥ 140/90 mmHg em duas ou mais medições',
    recommendation: 'Iniciar avaliação clínica completa. Considerar modificação do estilo de vida como primeira linha: redução de sódio (< 2g/dia), exercício aeróbico regular (150 min/semana), dieta DASH e redução de peso. Farmacoterapia indicada em hipertensão estágio 2 ou com alto risco cardiovascular.',
    evidenceLevel: 'A',
    priority: 1,
    source: 'Diretrizes Brasileiras de Hipertensão Arterial 2020 (SBC/SBH/SBN)',
    tags: ['hipertensão', 'pressão arterial', 'cardiovascular', 'DASH', 'sódio'],
  }),
  new ClinicalRule({
    id: 'rule-card-002',
    condition: 'LDL ≥ 190 mg/dL ou alto risco cardiovascular com LDL ≥ 70 mg/dL',
    category: 'CARDIOLOGY',
    recommendation: 'Iniciar tratamento com estatina de alta intensidade. Meta de LDL < 70 mg/dL em alto risco e < 50 mg/dL em risco muito alto. Associar ezetimiba se meta não atingida. Reavaliar perfil lipídico em 6-8 semanas após início do tratamento.',
    evidenceLevel: 'A',
    priority: 1,
    source: 'Diretriz Brasileira de Dislipidemia 2017 (SBDC/SBC)',
    tags: ['dislipidemia', 'LDL', 'colesterol', 'estatina', 'risco cardiovascular'],
  }),
  new ClinicalRule({
    id: 'rule-endo-001',
    category: 'ENDOCRINOLOGY',
    condition: 'Glicemia de jejum ≥ 126 mg/dL em dois exames ou HbA1c ≥ 6,5%',
    recommendation: 'Diagnóstico de Diabetes Mellitus confirmado. Iniciar educação em diabetes, plano alimentar individualizado, atividade física regular e monitoramento glicêmico. Metformina como primeiro agente farmacológico se sem contraindicações. Meta HbA1c < 7% para maioria dos adultos.',
    evidenceLevel: 'A',
    priority: 1,
    source: 'Diretriz da Sociedade Brasileira de Diabetes 2022-2023',
    tags: ['diabetes', 'glicemia', 'HbA1c', 'metformina', 'hiperglicemia'],
  }),
  new ClinicalRule({
    id: 'rule-endo-002',
    category: 'ENDOCRINOLOGY',
    condition: 'Glicemia de jejum 100-125 mg/dL ou HbA1c 5,7-6,4% (pré-diabetes)',
    recommendation: 'Intervenção intensiva no estilo de vida: perda de peso de 5-10%, dieta com redução de carboidratos refinados, atividade física ≥ 150 min/semana. Rastreamento anual. Considerar metformina em pacientes com alto risco de progressão.',
    evidenceLevel: 'A',
    priority: 2,
    source: 'American Diabetes Association Standards of Care 2024 / SBD 2022-2023',
    tags: ['pré-diabetes', 'prevenção', 'glicemia', 'estilo de vida', 'resistência insulínica'],
  }),
  new ClinicalRule({
    id: 'rule-nutr-001',
    category: 'NUTRITION',
    condition: 'IMC ≥ 25 kg/m² com padrão alimentar ultra-processado predominante',
    recommendation: 'Transição para dieta baseada em alimentos in natura e minimamente processados (Guia Alimentar Brasileiro). Aumentar consumo de vegetais, legumes, frutas, leguminosas e grãos integrais. Reduzir açúcares livres (< 10% das calorias totais) e gorduras saturadas (< 10%).',
    evidenceLevel: 'A',
    priority: 2,
    source: 'Guia Alimentar para a População Brasileira 2014 (MS) / WHO 2020',
    tags: ['nutrição', 'dieta', 'obesidade', 'ultra-processados', 'IMC', 'alimentação saudável'],
  }),
  new ClinicalRule({
    id: 'rule-exer-001',
    category: 'EXERCISE',
    condition: 'Sedentarismo (< 150 min/semana de atividade física moderada)',
    recommendation: 'Progressão gradual para 150-300 min/semana de atividade aeróbica moderada (ou 75-150 min intensa). Incluir treinamento de resistência muscular 2x/semana. Reduzir tempo sedentário total e inserir pausas ativas a cada 30 minutos.',
    evidenceLevel: 'A',
    priority: 2,
    source: 'WHO Physical Activity Guidelines 2020 / ACSM Guidelines 2022',
    tags: ['exercício', 'sedentarismo', 'atividade física', 'aeróbico', 'resistência', 'condicionamento'],
  }),
  new ClinicalRule({
    id: 'rule-sleep-001',
    category: 'SLEEP',
    condition: 'Qualidade do sono ruim: < 6h/noite ou fragmentação frequente do sono',
    recommendation: 'Implementar higiene do sono: horário regular de dormir e acordar, ambiente escuro e fresco (18-20°C), evitar telas 1h antes de dormir, limitar cafeína após 14h. Rastrear apneia do sono se roncador, sobrepeso ou sonolência diurna excessiva (escala de Epworth).',
    evidenceLevel: 'B',
    priority: 3,
    source: 'American Academy of Sleep Medicine / National Sleep Foundation 2023',
    tags: ['sono', 'insônia', 'higiene do sono', 'apneia', 'privação de sono', 'circadiano'],
  }),
  new ClinicalRule({
    id: 'rule-mental-001',
    category: 'MENTAL_HEALTH',
    condition: 'PHQ-9 ≥ 10 ou sintomas depressivos clinicamente relevantes por > 2 semanas',
    recommendation: 'Avaliação psicológica/psiquiátrica formal. Considerar psicoterapia (TCC como primeira linha). Antidepressivos indicados em depressão moderada/grave. Triagem de risco suicida obrigatória. Suporte de rede social e atividade física como adjuvantes.',
    evidenceLevel: 'A',
    priority: 1,
    source: 'DSM-5-TR / CFM / Protocolo de Manejo em Saúde Mental (MS 2022)',
    tags: ['depressão', 'PHQ-9', 'TCC', 'antidepressivo', 'saúde mental', 'psicoterapia'],
  }),
  new ClinicalRule({
    id: 'rule-metab-001',
    category: 'METABOLISM',
    condition: 'Síndrome metabólica: ≥ 3 critérios IDF/NCEP-ATP III presentes',
    recommendation: 'Intervenção multicomponente: perda de 7-10% do peso corporal, redução de carboidratos simples e gorduras saturadas, atividade física regular. Tratar cada componente individualmente (PA, glicemia, lipídeos). Monitorar PCR-ultrassensível como marcador de risco residual.',
    evidenceLevel: 'A',
    priority: 1,
    source: 'IDF 2006 / NCEP-ATP III / SBC 2020',
    tags: ['síndrome metabólica', 'obesidade abdominal', 'resistência insulínica', 'dislipidemia', 'PCR'],
  }),
  new ClinicalRule({
    id: 'rule-infla-001',
    category: 'INFLAMMATION',
    condition: 'PCR-ultrassensível > 2 mg/L sem causa infecciosa aguda identificada',
    recommendation: 'Investigar inflamação crônica de baixo grau: avaliação de estilo de vida (dieta pró-inflamatória, sedentarismo, tabagismo, estresse). Adotar padrão alimentar anti-inflamatório (mediterrâneo). Correção de disbiose intestinal. Otimizar sono e gestão de estresse. Rastrear causa autoimune se persistente.',
    evidenceLevel: 'B',
    priority: 3,
    source: 'JACC 2022 / European Heart Journal 2021',
    tags: ['inflamação', 'PCR', 'inflamação crônica', 'dieta mediterrânea', 'estilo de vida', 'autoimune'],
  }),
  new ClinicalRule({
    id: 'rule-geri-001',
    category: 'GERIATRICS',
    condition: 'Idoso ≥ 65 anos com polifarmácia (≥ 5 medicamentos)',
    recommendation: 'Revisão periódica da medicação usando critérios de Beers/STOPP-START. Desprescrição de medicamentos potencialmente inapropriados. Avaliar aderência, interações e reações adversas. Equipe multiprofissional incluindo farmacêutico clínico.',
    evidenceLevel: 'A',
    priority: 1,
    source: 'Critérios de Beers 2023 (AGS) / STOPP-START v3 2023',
    tags: ['geriatria', 'polifarmácia', 'idoso', 'Beers', 'desprescrição', 'medicamentos'],
  }),
  new ClinicalRule({
    id: 'rule-long-001',
    category: 'LONGEVITY',
    condition: 'Comprimento de telômeros abaixo do percentil 25 para a idade',
    recommendation: 'Otimizar determinantes de longevidade celular: reduzir estresse oxidativo (antioxidantes dietéticos, exercício), controlar inflamação crônica (dieta anti-inflamatória, PCR-us < 1 mg/L), qualidade do sono (> 7h), gestão de estresse (mindfulness, cortisol matinal). Evitar tabagismo e exposição a poluentes.',
    evidenceLevel: 'B',
    priority: 3,
    source: 'NEJM Longevity Review 2023 / Blackburn et al.',
    tags: ['longevidade', 'telômeros', 'senescência', 'antioxidantes', 'envelhecimento saudável'],
  }),
];
