import { PersonalizationRule, RuleCategory, EvidenceLevel } from '../entities/personalization-rule.entity.js';

export const BUILT_IN_PERSONALIZATION_RULES: PersonalizationRule[] = [
  new PersonalizationRule({
    id: 'pr-mediterranean-diet',
    category: RuleCategory.NUTRITION,
    condition: 'cardiovascular_risk',
    priority: 9,
    weight: 0.85,
    recommendation: 'Adotar dieta mediterrânea: azeite de oliva extra-virgem, peixes (2x/semana), legumes, verduras, frutas, nozes e grãos integrais; reduzir carnes vermelhas e processadas',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-dash-diet',
    category: RuleCategory.NUTRITION,
    condition: 'hypertension',
    priority: 9,
    weight: 0.90,
    recommendation: 'Dieta DASH: reduzir sódio (<2g/dia), aumentar potássio e magnésio (frutas, vegetais, laticínios com baixo teor de gordura), limitar álcool; meta PA < 130/80 mmHg',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-low-glycemic',
    category: RuleCategory.NUTRITION,
    condition: 'diabetes',
    priority: 9,
    weight: 0.90,
    recommendation: 'Dieta de baixo índice glicêmico: reduzir carboidratos simples, aumentar fibras (25-35g/dia), fracionar refeições em 5-6 pequenas porções; meta HbA1c < 7%',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-high-fiber',
    category: RuleCategory.NUTRITION,
    condition: 'metabolic_syndrome',
    priority: 8,
    weight: 0.80,
    recommendation: 'Aumentar consumo de fibras solúveis (>10g/dia): aveia, psyllium, legumes, maçã; reduzir carboidratos refinados e açúcares adicionados',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-omega3',
    category: RuleCategory.NUTRITION,
    condition: 'dyslipidemia',
    priority: 7,
    weight: 0.75,
    recommendation: 'Aumentar consumo de ômega-3: salmão/sardinha/atum 2-3x/semana ou suplementação de EPA+DHA (2-4g/dia) para redução de triglicerídeos em 20-40%',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-aerobic-exercise',
    category: RuleCategory.PHYSICAL_ACTIVITY,
    condition: 'cardiovascular_risk',
    priority: 9,
    weight: 0.90,
    recommendation: 'Exercício aeróbico moderado-intenso: 150-300 min/semana (caminhada rápida, ciclismo, natação); reduz risco cardiovascular em 20-35% e PA em 5-10 mmHg',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-resistance-training',
    category: RuleCategory.PHYSICAL_ACTIVITY,
    condition: 'diabetes',
    priority: 8,
    weight: 0.85,
    recommendation: 'Treinamento de resistência muscular 2-3x/semana (60-70% de 1RM): melhora sensibilidade à insulina em 15-35% e reduz HbA1c em média 0.5-0.6%',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-low-impact-exercise',
    category: RuleCategory.PHYSICAL_ACTIVITY,
    condition: 'obesity',
    priority: 8,
    weight: 0.85,
    recommendation: 'Exercício de baixo impacto (hidroginástica, ciclismo, caminhada): progressão gradual para 150-300 min/semana; objetivo de 5-10% redução de peso em 6 meses',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-increase-activity',
    category: RuleCategory.PHYSICAL_ACTIVITY,
    condition: 'sedentary',
    priority: 9,
    weight: 0.90,
    recommendation: 'Reduzir tempo sedentário: pausas ativas a cada 30 min, meta inicial de 7.000-10.000 passos/dia; progressão gradual para 150 min/semana de atividade moderada',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-glucose-monitoring',
    category: RuleCategory.MONITORING,
    condition: 'diabetes',
    priority: 10,
    weight: 1.0,
    recommendation: 'Monitorização glicêmica: glicemia capilar ou CGM conforme individualização; HbA1c a cada 3 meses até atingir meta (< 7%), depois semestral',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-bp-monitoring',
    category: RuleCategory.MONITORING,
    condition: 'hypertension',
    priority: 10,
    weight: 1.0,
    recommendation: 'Monitorização domiciliar da PA: 2 medições/dia por 7 dias antes das consultas; meta PA < 130/80 mmHg; registrar e levar ao médico',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-lipid-monitoring',
    category: RuleCategory.MONITORING,
    condition: 'dyslipidemia',
    priority: 8,
    weight: 0.85,
    recommendation: 'Perfil lipídico completo a cada 3-6 meses durante otimização terapêutica; meta LDL < 70 mg/dL para alto risco, < 50 mg/dL para muito alto risco',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-thyroid-screening',
    category: RuleCategory.MONITORING,
    condition: 'metabolic_syndrome',
    priority: 6,
    weight: 0.65,
    recommendation: 'Rastreamento anual de hipotireoidismo (TSH + T4 livre): hipotireoidismo subclínico agrava resistência insulínica, dislipidemia e ganho de peso',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-smoking-cessation',
    category: RuleCategory.LIFESTYLE,
    condition: 'smoking',
    priority: 10,
    weight: 1.0,
    recommendation: 'Cessação do tabagismo imediata: reduz RCV em 50% em 1 ano; combinar terapia de reposição nicotínica (TRN) + vareniclina ou bupropiona + suporte comportamental',
    evidenceLevel: EvidenceLevel.A,
  }),
  new PersonalizationRule({
    id: 'pr-alcohol-moderation',
    category: RuleCategory.LIFESTYLE,
    condition: 'cardiovascular_risk',
    priority: 7,
    weight: 0.70,
    recommendation: 'Moderação do álcool: máximo 1 drinque/dia (mulheres) ou 2 drinques/dia (homens); eliminar completamente se TG elevados, hepatopatia ou gestação',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-stress-management',
    category: RuleCategory.MENTAL_HEALTH,
    condition: 'high_stress',
    priority: 8,
    weight: 0.80,
    recommendation: 'Manejo do estresse: técnicas de relaxamento (mindfulness, respiração diafragmática), psicoterapia cognitivo-comportamental; reduz PA em 5-10 mmHg e cortisol crônico',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-mindfulness',
    category: RuleCategory.MENTAL_HEALTH,
    condition: 'high_stress',
    priority: 7,
    weight: 0.75,
    recommendation: 'Prática regular de mindfulness: 15-20 min/dia; benefícios documentados para controle glicêmico, PA e qualidade de vida em condições crônicas',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-sleep-apnea-screening',
    category: RuleCategory.SLEEP,
    condition: 'obesity',
    priority: 8,
    weight: 0.85,
    recommendation: 'Rastreamento de apneia obstrutiva do sono: escala de Epworth + polissonografia se suspeita; CPAP reduz PA e risco cardiovascular em 15-20%',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-sleep-hygiene',
    category: RuleCategory.SLEEP,
    condition: 'sleep_disorder',
    priority: 8,
    weight: 0.80,
    recommendation: 'Higiene do sono: horário regular, ambiente escuro e fresco (18-21°C), evitar telas 1h antes de dormir; meta 7-9h/noite; sono <6h aumenta RCV em 40% e resistência insulínica',
    evidenceLevel: EvidenceLevel.B,
  }),
  new PersonalizationRule({
    id: 'pr-statin-referral',
    category: RuleCategory.MEDICATION,
    condition: 'cardiovascular_risk',
    priority: 9,
    weight: 0.90,
    recommendation: 'Encaminhar para avaliação de estatina de alta intensidade se escore Framingham >10% ou LDL ≥ 190 mg/dL; reduz eventos cardiovasculares em 25-35%',
    evidenceLevel: EvidenceLevel.A,
  }),
];
