export enum DeviceCapability {
  WEIGHT                = 'WEIGHT',
  BODY_FAT              = 'BODY_FAT',
  BMI                   = 'BMI',
  MUSCLE_MASS           = 'MUSCLE_MASS',
  BONE_MASS             = 'BONE_MASS',
  BODY_WATER            = 'BODY_WATER',
  VISCERAL_FAT          = 'VISCERAL_FAT',
  BLOOD_PRESSURE        = 'BLOOD_PRESSURE',
  HEART_RATE            = 'HEART_RATE',
  OXYGEN_SATURATION     = 'OXYGEN_SATURATION',
  BLOOD_GLUCOSE         = 'BLOOD_GLUCOSE',
  BODY_TEMPERATURE      = 'BODY_TEMPERATURE',
  ECG                   = 'ECG',
  STEPS                 = 'STEPS',
  SLEEP                 = 'SLEEP',
  CALORIES              = 'CALORIES',
  HYDRATION             = 'HYDRATION',
  RESPIRATORY_RATE      = 'RESPIRATORY_RATE',
  STRESS_LEVEL          = 'STRESS_LEVEL',
}

export enum MeasurementType {
  WEIGHT        = 'WEIGHT',
  BODY_COMP     = 'BODY_COMP',
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  PULSE_OX      = 'PULSE_OX',
  HEART_RATE    = 'HEART_RATE',
  BLOOD_GLUCOSE = 'BLOOD_GLUCOSE',
  TEMPERATURE   = 'TEMPERATURE',
  ECG           = 'ECG',
  ACTIVITY      = 'ACTIVITY',
  SLEEP         = 'SLEEP',
  GENERIC       = 'GENERIC',
}
