import { MedicalConcept, ConceptCategory } from '../entities/medical-concept.entity.js';

export const BUILT_IN_CONCEPTS: MedicalConcept[] = [
  // ── Diseases ────────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-hypertension',
    code: 'I10',
    name: 'Hipertensão Arterial Sistêmica',
    description: 'Condição crônica caracterizada pela elevação persistente da pressão arterial (≥ 140/90 mmHg).',
    category: ConceptCategory.DISEASE,
    synonyms: ['HAS', 'pressão alta', 'hipertensão', 'hypertension'],
    metadata: { icdCode: 'I10', prevalenceBrazil: '32.5%', guideline: 'SBC 2020' },
  }),
  new MedicalConcept({
    id: 'concept-dm2',
    code: 'E11',
    name: 'Diabetes Mellitus Tipo 2',
    description: 'Distúrbio metabólico com hiperglicemia por resistência à insulina ou deficiência relativa na secreção.',
    category: ConceptCategory.DISEASE,
    synonyms: ['DM2', 'diabetes tipo 2', 'diabetes mellitus', 'type 2 diabetes'],
    metadata: { icdCode: 'E11', diagnosisCriteria: 'Glicemia ≥ 126 mg/dL ou HbA1c ≥ 6,5%' },
  }),
  new MedicalConcept({
    id: 'concept-obesity',
    code: 'E66',
    name: 'Obesidade',
    description: 'Condição crônica com IMC ≥ 30 kg/m². Associada a hipertensão, DM2, dislipidemia e apneia do sono.',
    category: ConceptCategory.DISEASE,
    synonyms: ['obeso', 'excesso de peso', 'obesity'],
    metadata: { icdCode: 'E66', bmiThreshold: 30 },
  }),
  new MedicalConcept({
    id: 'concept-metabolic-syndrome',
    code: 'E88.8',
    name: 'Síndrome Metabólica',
    description: 'Conjunto de ≥ 3 critérios: obesidade abdominal, TG ≥ 150 mg/dL, HDL baixo, PA ≥ 130/85 ou glicemia ≥ 100 mg/dL.',
    category: ConceptCategory.DISEASE,
    synonyms: ['SM', 'síndrome X', 'resistência insulínica', 'metabolic syndrome'],
    metadata: { icdCode: 'E88.8', minCriteria: 3 },
  }),
  new MedicalConcept({
    id: 'concept-dyslipidemia',
    code: 'E78',
    name: 'Dislipidemia',
    description: 'Alteração nos níveis de lipídeos séricos: LDL ≥ 130 mg/dL, TG ≥ 150 mg/dL ou HDL < 40 (H) / < 50 (M) mg/dL.',
    category: ConceptCategory.DISEASE,
    synonyms: ['colesterol alto', 'hiperlipidemia', 'dyslipidemia'],
    metadata: { icdCode: 'E78' },
  }),
  new MedicalConcept({
    id: 'concept-atherosclerosis',
    code: 'I70',
    name: 'Aterosclerose',
    description: 'Acúmulo de placas de ateroma na parede arterial, reduzindo o fluxo sanguíneo. Principal base da DAC.',
    category: ConceptCategory.DISEASE,
    synonyms: ['aterosclerose coronariana', 'placas ateromatosas', 'atherosclerosis'],
    metadata: { icdCode: 'I70' },
  }),
  new MedicalConcept({
    id: 'concept-cad',
    code: 'I25',
    name: 'Doença Arterial Coronariana',
    description: 'Obstrução das artérias coronárias por aterosclerose, causando angina, infarto e insuficiência cardíaca.',
    category: ConceptCategory.DISEASE,
    synonyms: ['DAC', 'doença coronariana', 'angina', 'coronary artery disease'],
    metadata: { icdCode: 'I25' },
  }),
  new MedicalConcept({
    id: 'concept-heart-failure',
    code: 'I50',
    name: 'Insuficiência Cardíaca',
    description: 'Incapacidade do coração de bombear sangue suficiente para suprir as necessidades do organismo.',
    category: ConceptCategory.DISEASE,
    synonyms: ['IC', 'insuficiência cardíaca congestiva', 'heart failure'],
    metadata: { icdCode: 'I50' },
  }),
  new MedicalConcept({
    id: 'concept-ckd',
    code: 'N18',
    name: 'Doença Renal Crônica',
    description: 'Perda progressiva da função renal por ≥ 3 meses. Estadiada por TFG (G1-G5) e albuminúria.',
    category: ConceptCategory.DISEASE,
    synonyms: ['DRC', 'insuficiência renal crônica', 'chronic kidney disease'],
    metadata: { icdCode: 'N18' },
  }),
  new MedicalConcept({
    id: 'concept-hypothyroidism',
    code: 'E03.9',
    name: 'Hipotireoidismo',
    description: 'Produção insuficiente de hormônios tireoidianos. TSH elevado, T4L reduzido.',
    category: ConceptCategory.DISEASE,
    synonyms: ['tireoidite de Hashimoto', 'hypothyroidism'],
    metadata: { icdCode: 'E03.9', diagnosis: 'TSH > 4,0 mUI/L + T4L baixo' },
  }),

  // ── Symptoms ────────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-fatigue',
    code: 'R53',
    name: 'Fadiga',
    description: 'Cansaço persistente e desproporcional ao esforço. Pode indicar anemia, hipotireoidismo, DM2 ou depressão.',
    category: ConceptCategory.SYMPTOM,
    synonyms: ['cansaço', 'astenia', 'fatigue', 'fraqueza'],
  }),
  new MedicalConcept({
    id: 'concept-chest-pain',
    code: 'R07',
    name: 'Dor Torácica',
    description: 'Dor ou desconforto no tórax. Sinal de alarme para DAC, dissecção aórtica ou TEP.',
    category: ConceptCategory.SYMPTOM,
    synonyms: ['dor no peito', 'angina', 'chest pain'],
  }),
  new MedicalConcept({
    id: 'concept-dyspnea',
    code: 'R06.0',
    name: 'Dispneia',
    description: 'Dificuldade respiratória. Ocorre em insuficiência cardíaca, doença pulmonar e anemia.',
    category: ConceptCategory.SYMPTOM,
    synonyms: ['falta de ar', 'dispnéia', 'dyspnea', 'shortness of breath'],
  }),
  new MedicalConcept({
    id: 'concept-polyuria',
    code: 'R35',
    name: 'Poliúria',
    description: 'Excreção de volume urinário > 3L/dia. Clássico sintoma do diabetes não controlado.',
    category: ConceptCategory.SYMPTOM,
    synonyms: ['aumento da diurese', 'urinar muito', 'polyuria'],
  }),
  new MedicalConcept({
    id: 'concept-polydipsia',
    code: 'R63.1',
    name: 'Polidipsia',
    description: 'Sede excessiva, frequentemente associada à poliúria no DM2 descompensado.',
    category: ConceptCategory.SYMPTOM,
    synonyms: ['sede excessiva', 'polydipsia'],
  }),

  // ── Biomarkers ──────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-ldl',
    code: '2089-1',
    name: 'LDL Colesterol',
    description: 'Lipoproteína de baixa densidade. Principal fator de risco para aterosclerose. Meta < 70 mg/dL em alto risco.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['LDL-C', 'colesterol ruim', 'LDL cholesterol'],
    metadata: { loincCode: '2089-1', unit: 'mg/dL', normalRange: '< 130 mg/dL' },
  }),
  new MedicalConcept({
    id: 'concept-hdl',
    code: '2085-9',
    name: 'HDL Colesterol',
    description: 'Lipoproteína de alta densidade. Fator protetor cardiovascular. Baixo < 40 (H) / < 50 (M) mg/dL.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['HDL-C', 'colesterol bom', 'HDL cholesterol'],
    metadata: { loincCode: '2085-9', unit: 'mg/dL' },
  }),
  new MedicalConcept({
    id: 'concept-triglycerides',
    code: '2571-8',
    name: 'Triglicerídeos',
    description: 'Gorduras circulantes no sangue. Elevados (≥ 150 mg/dL) indicam risco metabólico e cardiovascular.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['TG', 'triglicérides', 'triglycerides'],
    metadata: { loincCode: '2571-8', unit: 'mg/dL', threshold: 150 },
  }),
  new MedicalConcept({
    id: 'concept-fasting-glucose',
    code: '1558-6',
    name: 'Glicemia de Jejum',
    description: 'Concentração de glicose no sangue após 8h de jejum. Normal < 100 mg/dL; pré-DM 100-125; DM ≥ 126 mg/dL.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['glicose em jejum', 'fasting glucose', 'glicemia'],
    metadata: { loincCode: '1558-6', unit: 'mg/dL', normalMax: 99, preDM: '100-125', dm: '≥ 126' },
  }),
  new MedicalConcept({
    id: 'concept-hba1c',
    code: '4548-4',
    name: 'Hemoglobina Glicada (HbA1c)',
    description: 'Média glicêmica dos últimos 2-3 meses. Normal < 5,7%; pré-DM 5,7-6,4%; DM ≥ 6,5%.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['HbA1c', 'A1c', 'hemoglobina glicada', 'glycated hemoglobin'],
    metadata: { loincCode: '4548-4', unit: '%', target: '< 7% (DM controlado)' },
  }),
  new MedicalConcept({
    id: 'concept-crp',
    code: '1988-5',
    name: 'PCR Ultrassensível',
    description: 'Marcador inflamatório. Baixo < 1 mg/L (baixo risco CV); moderado 1-3; alto > 3 mg/L.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['PCR-us', 'CRP', 'proteína C-reativa', 'high-sensitivity CRP'],
    metadata: { loincCode: '1988-5', unit: 'mg/L', cardiovascularRisk: { low: '<1', moderate: '1-3', high: '>3' } },
  }),
  new MedicalConcept({
    id: 'concept-bmi',
    code: '39156-5',
    name: 'Índice de Massa Corporal',
    description: 'IMC = peso(kg) / altura²(m). Normal 18,5-24,9; sobrepeso 25-29,9; obesidade ≥ 30.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['IMC', 'BMI', 'body mass index'],
    metadata: { loincCode: '39156-5', unit: 'kg/m²', normal: '18.5-24.9', overweight: '25-29.9', obese: '≥ 30' },
  }),
  new MedicalConcept({
    id: 'concept-systolic-bp',
    code: '8480-6',
    name: 'Pressão Arterial Sistólica',
    description: 'Pressão máxima exercida pelo sangue nas artérias. Normal < 120 mmHg; pré-HAS 120-139; HAS ≥ 140 mmHg.',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['PAS', 'sistólica', 'systolic blood pressure'],
    metadata: { loincCode: '8480-6', unit: 'mmHg', normal: '< 120', hypertension: '≥ 140' },
  }),
  new MedicalConcept({
    id: 'concept-tsh',
    code: '3016-3',
    name: 'TSH (Hormônio Tireotrófico)',
    description: 'Hormônio hipofisário regulador da tireoide. Elevado no hipotireoidismo (> 4,0 mUI/L).',
    category: ConceptCategory.BIOMARKER,
    synonyms: ['TSH', 'tireotrofina', 'thyroid stimulating hormone'],
    metadata: { loincCode: '3016-3', unit: 'mUI/L', normalRange: '0.4-4.0' },
  }),

  // ── Medications ─────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-metformin',
    code: 'RxNorm:6809',
    name: 'Metformina',
    description: 'Biguanida de primeira linha para DM2. Reduz resistência insulínica, HbA1c e eventos cardiovasculares.',
    category: ConceptCategory.MEDICATION,
    synonyms: ['glucoformin', 'glifage', 'metformin'],
    metadata: { rxcui: '6809', classATC: 'A10BA02', mechanismOfAction: 'Inibe gliconeogênese hepática' },
  }),
  new MedicalConcept({
    id: 'concept-statins',
    code: 'RxNorm:41493',
    name: 'Estatinas',
    description: 'Inibidores da HMG-CoA redutase. Reduzem LDL em 30-50%. Prevenção CV primária e secundária.',
    category: ConceptCategory.MEDICATION,
    synonyms: ['sinvastatina', 'atorvastatina', 'rosuvastatina', 'statins'],
    metadata: { classATC: 'C10AA', ldlReduction: '30-50%' },
  }),
  new MedicalConcept({
    id: 'concept-ace-inhibitors',
    code: 'RxNorm:18996',
    name: 'Inibidores da ECA',
    description: 'Anti-hipertensivos que bloqueiam a enzima conversora de angiotensina. Nefroprotetores no DM.',
    category: ConceptCategory.MEDICATION,
    synonyms: ['captopril', 'enalapril', 'lisinopril', 'IECA', 'ACE inhibitors'],
    metadata: { classATC: 'C09AA', indications: ['hipertensão', 'insuficiência cardíaca', 'nefropatia diabética'] },
  }),

  // ── Nutrients ───────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-omega3',
    code: 'NUT-001',
    name: 'Ômega-3',
    description: 'Ácidos graxos poli-insaturados (EPA+DHA). Reduzem triglicerídeos, inflamação e risco cardiovascular.',
    category: ConceptCategory.NUTRIENT,
    synonyms: ['EPA', 'DHA', 'ácidos graxos ômega-3', 'omega-3 fatty acids', 'peixe'],
    metadata: { dose: '1-4g/dia', sources: ['peixes gordurosos', 'chia', 'linhaça'] },
  }),
  new MedicalConcept({
    id: 'concept-dietary-fiber',
    code: 'NUT-002',
    name: 'Fibra Alimentar',
    description: 'Polissacarídeos não digeríveis. Reduzem glicemia pós-prandial, colesterol LDL e risco de DM2.',
    category: ConceptCategory.NUTRIENT,
    synonyms: ['fibras', 'dietary fiber', 'fibra dietética'],
    metadata: { recommendation: '25-38g/dia', sources: ['legumes', 'frutas', 'cereais integrais'] },
  }),
  new MedicalConcept({
    id: 'concept-vitamin-d',
    code: 'NUT-003',
    name: 'Vitamina D',
    description: 'Vitamina lipossolúvel com papel na homeostase do cálcio, imunidade e regulação metabólica.',
    category: ConceptCategory.NUTRIENT,
    synonyms: ['calciferol', 'colecalciferol', 'vitamin D', 'D3'],
    metadata: { adequateLevel: '> 30 ng/mL', deficiency: '< 20 ng/mL' },
  }),

  // ── Lifestyle ────────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-sedentary',
    code: 'Z72.3',
    name: 'Sedentarismo',
    description: 'Menos de 150 min/semana de atividade física moderada. Fator de risco independente para todas as DCNT.',
    category: ConceptCategory.LIFESTYLE,
    synonyms: ['inatividade física', 'sedentary lifestyle', 'falta de exercício'],
    metadata: { icdCode: 'Z72.3', definition: '< 150 min/sem de atividade moderada' },
  }),
  new MedicalConcept({
    id: 'concept-smoking',
    code: 'Z87.891',
    name: 'Tabagismo',
    description: 'Uso de tabaco. Principal causa modificável de câncer, DAC, DPOC e AVC.',
    category: ConceptCategory.LIFESTYLE,
    synonyms: ['fumar', 'cigarro', 'nicotina', 'smoking', 'tobacco'],
    metadata: { icdCode: 'F17', attributableMortality: '12% global' },
  }),
  new MedicalConcept({
    id: 'concept-high-sodium',
    code: 'Z72.4',
    name: 'Dieta Rica em Sódio',
    description: 'Ingestão de sódio > 2g/dia (5g de sal). Eleva a pressão arterial em indivíduos sensíveis ao sódio.',
    category: ConceptCategory.LIFESTYLE,
    synonyms: ['excesso de sal', 'high sodium diet', 'dieta hipersódica'],
    metadata: { whoLimit: '< 2g/dia', brazilianAverage: '~ 4g/dia' },
  }),

  // ── Exercise ─────────────────────────────────────────────────────────────────
  new MedicalConcept({
    id: 'concept-aerobic',
    code: 'EX-001',
    name: 'Exercício Aeróbico',
    description: 'Atividade de intensidade moderada a vigorosa por ≥ 150 min/semana. Reduz PA, glicemia e mortalidade CV.',
    category: ConceptCategory.EXERCISE,
    synonyms: ['cardio', 'caminhada', 'corrida', 'natação', 'aerobic exercise'],
    metadata: { who2020Recommendation: '150-300 min/semana de intensidade moderada' },
  }),
  new MedicalConcept({
    id: 'concept-resistance',
    code: 'EX-002',
    name: 'Treinamento de Resistência',
    description: 'Exercícios contra resistência 2-3x/semana. Aumenta massa muscular, reduz glicemia e melhora composição corporal.',
    category: ConceptCategory.EXERCISE,
    synonyms: ['musculação', 'força', 'resistance training', 'weight training'],
    metadata: { recommendation: '2-3x/semana, todos grupos musculares' },
  }),
];
