import { EvidenceRating, GradeQuality, RecommendationStrength, RiskOfBias } from '../entities/evidence-rating.entity.js';

export const BUILT_IN_RATINGS: EvidenceRating[] = [
  new EvidenceRating({
    id: 'rating-statin-meta-2022',
    evidenceId: 'ev-statin-meta-2022',
    grade: GradeQuality.HIGH,
    quality: 95,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-metformin-cochrane-2023',
    evidenceId: 'ev-metformin-cochrane-2023',
    grade: GradeQuality.HIGH,
    quality: 92,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-exercise-cardio-meta-2021',
    evidenceId: 'ev-exercise-cardio-meta-2021',
    grade: GradeQuality.HIGH,
    quality: 88,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-mediterranean-meta-2019',
    evidenceId: 'ev-mediterranean-meta-2019',
    grade: GradeQuality.MODERATE,
    quality: 82,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-dash-hypertension-sr-2020',
    evidenceId: 'ev-dash-hypertension-sr-2020',
    grade: GradeQuality.HIGH,
    quality: 90,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-omega3-cardio-meta-2021',
    evidenceId: 'ev-omega3-cardio-meta-2021',
    grade: GradeQuality.MODERATE,
    quality: 78,
    strength: RecommendationStrength.CONDITIONAL,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-sleep-cardio-sr-2021',
    evidenceId: 'ev-sleep-cardio-sr-2021',
    grade: GradeQuality.MODERATE,
    quality: 75,
    strength: RecommendationStrength.CONDITIONAL,
    riskOfBias: RiskOfBias.MODERATE,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-fiber-glycemic-meta-2020',
    evidenceId: 'ev-fiber-glycemic-meta-2020',
    grade: GradeQuality.MODERATE,
    quality: 80,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-ace-heartfailure-cochrane-2023',
    evidenceId: 'ev-ace-heartfailure-cochrane-2023',
    grade: GradeQuality.HIGH,
    quality: 93,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-vitd-metabolic-meta-2022',
    evidenceId: 'ev-vitd-metabolic-meta-2022',
    grade: GradeQuality.LOW,
    quality: 60,
    strength: RecommendationStrength.CONDITIONAL,
    riskOfBias: RiskOfBias.MODERATE,
    consistency: 'INCONSISTENT',
    directness: 'INDIRECT',
    precision: 'IMPRECISE',
  }),

  new EvidenceRating({
    id: 'rating-sprint-2015',
    evidenceId: 'ev-sprint-2015',
    grade: GradeQuality.HIGH,
    quality: 91,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-accord-2008',
    evidenceId: 'ev-accord-2008',
    grade: GradeQuality.HIGH,
    quality: 89,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-predimed-2013',
    evidenceId: 'ev-predimed-2013',
    grade: GradeQuality.HIGH,
    quality: 87,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-smoking-cv-cohort-2019',
    evidenceId: 'ev-smoking-cv-cohort-2019',
    grade: GradeQuality.MODERATE,
    quality: 76,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.MODERATE,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-sedentary-mortality-cohort-2020',
    evidenceId: 'ev-sedentary-mortality-cohort-2020',
    grade: GradeQuality.MODERATE,
    quality: 74,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.MODERATE,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-resistance-insulin-rct-2021',
    evidenceId: 'ev-resistance-insulin-rct-2021',
    grade: GradeQuality.MODERATE,
    quality: 79,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-hba1c-microvascular-rct-2018',
    evidenceId: 'ev-hba1c-microvascular-rct-2018',
    grade: GradeQuality.HIGH,
    quality: 88,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-obesity-interventions-meta-2022',
    evidenceId: 'ev-obesity-interventions-meta-2022',
    grade: GradeQuality.HIGH,
    quality: 85,
    strength: RecommendationStrength.STRONG,
    riskOfBias: RiskOfBias.LOW,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'PRECISE',
  }),

  new EvidenceRating({
    id: 'rating-crp-cardiac-cohort-2018',
    evidenceId: 'ev-crp-cardiac-cohort-2018',
    grade: GradeQuality.MODERATE,
    quality: 72,
    strength: RecommendationStrength.CONDITIONAL,
    riskOfBias: RiskOfBias.MODERATE,
    consistency: 'CONSISTENT',
    directness: 'DIRECT',
    precision: 'IMPRECISE',
  }),

  new EvidenceRating({
    id: 'rating-tsh-metabolic-cohort-2020',
    evidenceId: 'ev-tsh-metabolic-cohort-2020',
    grade: GradeQuality.LOW,
    quality: 62,
    strength: RecommendationStrength.CONDITIONAL,
    riskOfBias: RiskOfBias.MODERATE,
    consistency: 'CONSISTENT',
    directness: 'INDIRECT',
    precision: 'IMPRECISE',
  }),
];
