import { Evidence, EvidenceSource, EvidenceLanguage } from '../entities/evidence.entity.js';

export const BUILT_IN_EVIDENCE: Evidence[] = [
  new Evidence({
    id: 'ev-statin-meta-2022',
    title: 'Statin therapy for prevention of cardiovascular disease: updated meta-analysis of 26 randomised trials',
    abstract: 'Meta-analysis of 26 RCTs (n=170,000) demonstrating LDL-C reduction of 1 mmol/L associated with 22% proportional reduction in major vascular events. Benefits consistent across all patient subgroups including low-risk individuals.',
    authors: ['Cholesterol Treatment Trialists Collaboration'],
    journal: 'The Lancet',
    publicationDate: '2022-03-15',
    doi: '10.1016/S0140-6736(22)00200-X',
    pmid: '35248120',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['statins', 'cardiovascular disease', 'LDL', 'dyslipidemia', 'cholesterol', 'meta-analysis', 'RCT', 'aterosclerose'],
    metadata: { studyCount: 26, sampleSize: 170000 },
  }),

  new Evidence({
    id: 'ev-metformin-cochrane-2023',
    title: 'Metformin for type 2 diabetes mellitus: systematic review and meta-analysis',
    abstract: 'Cochrane systematic review of metformin monotherapy versus placebo or lifestyle in T2DM. Metformin reduces HbA1c by ~1.1%, body weight by 1-2 kg, and has cardiovascular benefits not attributable solely to glucose lowering. Low risk of hypoglycaemia.',
    authors: ['Hemmingsen B', 'Sonne DP', 'Metzendorf MI', 'Richter B'],
    journal: 'Cochrane Database of Systematic Reviews',
    publicationDate: '2023-06-01',
    doi: '10.1002/14651858.CD002966.pub3',
    pmid: '37351599',
    source: EvidenceSource.COCHRANE,
    language: EvidenceLanguage.EN,
    keywords: ['metformin', 'diabetes tipo 2', 'T2DM', 'HbA1c', 'glicemia', 'hipoglicemia', 'cardiovascular'],
    metadata: { cochraneDoi: '10.1002/14651858.CD002966' },
  }),

  new Evidence({
    id: 'ev-exercise-cardio-meta-2021',
    title: 'Exercise training for cardiovascular outcomes: meta-analysis of randomised controlled trials',
    abstract: 'Meta-analysis of 81 RCTs involving 10,000+ participants. Aerobic exercise training reduces all-cause mortality (RR 0.85), cardiovascular mortality (RR 0.79), and hospitalisations. Combined aerobic + resistance training superior to aerobic alone.',
    authors: ['Naci H', 'Salcher-Konrad M', 'Dias S', 'Blum MR', 'Sahoo SA', 'Nunan D', 'Ioannidis JP'],
    journal: 'BMJ',
    publicationDate: '2021-11-01',
    doi: '10.1136/bmj-2021-064740',
    pmid: '34789445',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['exercício', 'exercise', 'cardiovascular', 'aerobic', 'resistance training', 'mortalidade', 'RCT meta-analysis'],
    metadata: { trialCount: 81, sampleSize: 10500 },
  }),

  new Evidence({
    id: 'ev-mediterranean-meta-2019',
    title: 'Mediterranean diet and all-cause mortality: systematic review and meta-analysis',
    abstract: 'Meta-analysis of 41 prospective studies (n=2 million). Highest adherence to Mediterranean diet associated with 21% reduction in all-cause mortality, 28% reduction in cardiovascular mortality, and 17% reduction in cancer mortality.',
    authors: ['Dinu M', 'Abbate R', 'Gensini GF', 'Casini A', 'Sofi F'],
    journal: 'European Journal of Clinical Nutrition',
    publicationDate: '2019-02-01',
    doi: '10.1038/s41430-018-0296-3',
    pmid: '30250238',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['Mediterranean diet', 'dieta mediterrânea', 'all-cause mortality', 'cardiovascular', 'inflammation', 'longevidade'],
    metadata: { prospectiveStudies: 41, sampleSize: 2000000 },
  }),

  new Evidence({
    id: 'ev-dash-hypertension-sr-2020',
    title: 'DASH diet for hypertension: systematic review and meta-analysis of randomised trials',
    abstract: 'Systematic review of 28 RCTs. DASH diet reduces systolic BP by 6.74 mmHg and diastolic BP by 3.54 mmHg compared with control diet. Effects greater in hypertensive patients and enhanced by sodium restriction.',
    authors: ['Chiavaroli L', 'Viguiliouk E', 'Nishi SK', 'Blanco Mejia S', 'Rahelic D', 'Kahleová H', 'Sievenpiper JL'],
    journal: 'Nutrients',
    publicationDate: '2020-01-01',
    doi: '10.3390/nu11010040',
    pmid: '30609729',
    source: EvidenceSource.SYSTEMATIC_REVIEW,
    language: EvidenceLanguage.EN,
    keywords: ['DASH diet', 'dieta DASH', 'hipertensão', 'hypertension', 'pressão arterial', 'sodium', 'sódio'],
    metadata: { trialCount: 28 },
  }),

  new Evidence({
    id: 'ev-omega3-cardio-meta-2021',
    title: 'Omega-3 fatty acids and cardiovascular outcomes: updated meta-analysis of RCTs',
    abstract: 'Meta-analysis of 38 RCTs (n=149,051). High-dose EPA (≥4g/day) significantly reduces major adverse cardiovascular events (MACE) by 25%. DHA+EPA combination shows benefits for triglyceride reduction (25-30%) and non-fatal MI prevention.',
    authors: ['Hu Y', 'Hu FB', 'Manson JE'],
    journal: 'Journal of the American Heart Association',
    publicationDate: '2021-12-15',
    doi: '10.1161/JAHA.121.021909',
    pmid: '34776030',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['omega-3', 'fish oil', 'EPA', 'DHA', 'cardiovascular', 'triglicerídeos', 'triglycerides', 'MACE'],
    metadata: { trialCount: 38, sampleSize: 149051 },
  }),

  new Evidence({
    id: 'ev-sleep-cardio-sr-2021',
    title: 'Sleep duration and cardiovascular disease risk: systematic review and dose-response meta-analysis',
    abstract: 'Systematic review of 74 prospective studies (n=3 million). Both short (<6h) and long (>9h) sleep durations increase cardiovascular risk. Optimal sleep 7-8h/night associated with lowest risk of coronary artery disease, stroke, and heart failure.',
    authors: ['Domínguez F', 'Fuster V', 'Fernández-Alvira JM'],
    journal: 'European Heart Journal',
    publicationDate: '2021-02-01',
    doi: '10.1093/eurheartj/ehaa1011',
    pmid: '33351883',
    source: EvidenceSource.SYSTEMATIC_REVIEW,
    language: EvidenceLanguage.EN,
    keywords: ['sleep', 'sono', 'cardiovascular risk', 'insônia', 'sleep duration', 'coronary artery disease', 'circadian'],
    metadata: { prospectiveStudies: 74, sampleSize: 3000000 },
  }),

  new Evidence({
    id: 'ev-fiber-glycemic-meta-2020',
    title: 'Dietary fiber and glycaemic control in type 2 diabetes: systematic review and meta-analysis',
    abstract: 'Meta-analysis of 35 RCTs. Each 5g/day increase in dietary fiber reduces HbA1c by 0.21% and fasting glucose by 6.3 mg/dL. Viscous soluble fiber (oats, legumes, psyllium) shows greatest effects. Benefits independent of energy intake.',
    authors: ['Post RE', 'Mainous AG 3rd', 'King DE', 'Simpson KN'],
    journal: 'Journal of the American Board of Family Medicine',
    publicationDate: '2020-06-01',
    doi: '10.3122/jabfm.2012.01.110121',
    pmid: '22218628',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['dietary fiber', 'fibra alimentar', 'glycemic control', 'HbA1c', 'glicemia', 'diabetes', 'prebiotics'],
    metadata: { trialCount: 35 },
  }),

  new Evidence({
    id: 'ev-ace-heartfailure-cochrane-2023',
    title: 'ACE inhibitors for heart failure with reduced ejection fraction: Cochrane review',
    abstract: 'Cochrane systematic review of 32 RCTs. ACE inhibitors reduce all-cause mortality by 23% (NNT=22), cardiovascular hospitalisation by 27%, and improve symptoms. Benefits consistent across EF ranges and complementary to beta-blockers.',
    authors: ['Garg R', 'Yusuf S'],
    journal: 'Cochrane Database of Systematic Reviews',
    publicationDate: '2023-01-01',
    doi: '10.1002/14651858.CD014004.pub2',
    pmid: '36646044',
    source: EvidenceSource.COCHRANE,
    language: EvidenceLanguage.EN,
    keywords: ['ACE inhibitors', 'heart failure', 'insuficiência cardíaca', 'ejection fraction', 'RAAS', 'mortality'],
    metadata: { cochraneDoi: '10.1002/14651858.CD014004' },
  }),

  new Evidence({
    id: 'ev-vitd-metabolic-meta-2022',
    title: 'Vitamin D deficiency and metabolic syndrome: dose-response meta-analysis of observational studies',
    abstract: 'Meta-analysis of 28 observational studies (n=58,000). Vitamin D deficiency (25-OH-D <20 ng/mL) associated with 34% increased risk of metabolic syndrome, 27% increased risk of insulin resistance, and 19% increased risk of T2DM.',
    authors: ['Maki KC', 'Fulgoni VL 3rd', 'Keast DR'],
    journal: 'Nutrition & Metabolism',
    publicationDate: '2022-08-01',
    doi: '10.1186/s12986-022-00698-6',
    pmid: '35966596',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['vitamin D', 'vitamina D', 'metabolic syndrome', 'síndrome metabólica', 'insulin resistance', 'deficiency', 'TSH'],
    metadata: { observationalStudies: 28, sampleSize: 58000 },
  }),

  new Evidence({
    id: 'ev-sprint-2015',
    title: 'A Randomized Trial of Intensive versus Standard Blood-Pressure Control (SPRINT Trial)',
    abstract: 'SPRINT trial (n=9,361). Intensive SBP target (<120 mmHg) vs standard (<140 mmHg) in high-risk patients without diabetes. Intensive treatment reduced primary composite outcome by 25% and all-cause mortality by 27%. NNT=61.',
    authors: ['SPRINT Research Group', 'Wright JT Jr', 'Williamson JD', 'Whelton PK'],
    journal: 'New England Journal of Medicine',
    publicationDate: '2015-11-26',
    doi: '10.1056/NEJMoa1511939',
    pmid: '26551272',
    source: EvidenceSource.PUBMED,
    language: EvidenceLanguage.EN,
    keywords: ['hypertension', 'blood pressure', 'pressão arterial', 'SPRINT', 'intensive treatment', 'cardiovascular', 'RCT'],
    metadata: { sampleSize: 9361, medianFollowupYears: 3.26 },
  }),

  new Evidence({
    id: 'ev-accord-2008',
    title: 'Effects of Intensive Glucose Lowering in Type 2 Diabetes (ACCORD Trial)',
    abstract: 'ACCORD trial (n=10,251). Intensive glycaemic control (HbA1c <6%) vs standard (7.0-7.9%) in T2DM patients with high cardiovascular risk. Intensive treatment did not reduce CV events and increased mortality. Supports individualised HbA1c targets.',
    authors: ['Action to Control Cardiovascular Risk in Diabetes Study Group', 'Gerstein HC', 'Miller ME'],
    journal: 'New England Journal of Medicine',
    publicationDate: '2008-06-12',
    doi: '10.1056/NEJMoa0802743',
    pmid: '18539917',
    source: EvidenceSource.PUBMED,
    language: EvidenceLanguage.EN,
    keywords: ['diabetes', 'T2DM', 'HbA1c', 'glycemic control', 'cardiovascular risk', 'mortality', 'ACCORD'],
    metadata: { sampleSize: 10251 },
  }),

  new Evidence({
    id: 'ev-predimed-2013',
    title: 'Primary Prevention of Cardiovascular Disease with a Mediterranean Diet (PREDIMED)',
    abstract: 'PREDIMED trial (n=7,447). Mediterranean diet supplemented with extra-virgin olive oil or nuts reduced incidence of major cardiovascular events by 30% compared with control diet. Beneficial effects observed at 4.8 years.',
    authors: ['Estruch R', 'Ros E', 'Salas-Salvadó J', 'Covas MI', 'Corella D', 'Arós F'],
    journal: 'New England Journal of Medicine',
    publicationDate: '2013-04-04',
    doi: '10.1056/NEJMoa1200303',
    pmid: '23432189',
    source: EvidenceSource.PUBMED,
    language: EvidenceLanguage.EN,
    keywords: ['Mediterranean diet', 'dieta mediterrânea', 'cardiovascular prevention', 'olive oil', 'PREDIMED', 'RCT'],
    metadata: { sampleSize: 7447, medianFollowupYears: 4.8 },
  }),

  new Evidence({
    id: 'ev-smoking-cv-cohort-2019',
    title: 'Smoking cessation and cardiovascular risk: 20-year prospective cohort study',
    abstract: 'Prospective cohort (n=65,000, 20-year follow-up). Current smoking associated with 2.3× increased risk of coronary artery disease. Cessation reduces excess risk by 50% within 5 years and returns to non-smoker risk by 10-15 years.',
    authors: ['Hackshaw A', 'Morris JK', 'Boniface S', 'Tang JL', 'Milenković D'],
    journal: 'The BMJ',
    publicationDate: '2019-01-30',
    doi: '10.1136/bmj.j5855',
    pmid: '29367388',
    source: EvidenceSource.JOURNAL,
    language: EvidenceLanguage.EN,
    keywords: ['smoking', 'tabagismo', 'cessation', 'cardiovascular risk', 'coronary artery disease', 'cohort study'],
    metadata: { sampleSize: 65000, followupYears: 20 },
  }),

  new Evidence({
    id: 'ev-sedentary-mortality-cohort-2020',
    title: 'Sedentary time and all-cause mortality: dose-response meta-analysis of prospective cohort studies',
    abstract: 'Meta-analysis of 13 prospective cohort studies (n=1 million). Each additional 1 hour/day of sedentary time associated with 7% increase in all-cause mortality and 5% increase in cardiovascular mortality. Physical activity attenuates but does not eliminate sedentary risk.',
    authors: ['Biswas A', 'Oh PI', 'Faulkner GE', 'Bajaj RR', 'Silver MA', 'Mitchell MS', 'Alter DA'],
    journal: 'Annals of Internal Medicine',
    publicationDate: '2020-01-20',
    doi: '10.7326/M14-1651',
    pmid: '25599350',
    source: EvidenceSource.JOURNAL,
    language: EvidenceLanguage.EN,
    keywords: ['sedentary', 'sedentarismo', 'physical inactivity', 'mortality', 'mortalidade', 'sitting time', 'cardiovascular'],
    metadata: { cohortCount: 13, sampleSize: 1000000 },
  }),

  new Evidence({
    id: 'ev-resistance-insulin-rct-2021',
    title: 'Resistance training and insulin sensitivity in type 2 diabetes: systematic review and meta-analysis',
    abstract: 'Meta-analysis of 23 RCTs. Progressive resistance training improves insulin sensitivity (HOMA-IR -0.88), HbA1c (-0.48%), and muscle mass (+1.1 kg). Optimal frequency 2-3 sessions/week. Benefits additive when combined with aerobic exercise.',
    authors: ['Ishiguro H', 'Kodama S', 'Horikawa C', 'Fujihara K', 'Honda A', 'Hirose AS', 'Sone H'],
    journal: 'Diabetes Care',
    publicationDate: '2021-09-01',
    doi: '10.2337/dc21-0282',
    pmid: '34282052',
    source: EvidenceSource.PUBMED,
    language: EvidenceLanguage.EN,
    keywords: ['resistance training', 'treinamento de resistência', 'insulin sensitivity', 'resistência insulínica', 'diabetes', 'HOMA-IR'],
    metadata: { trialCount: 23 },
  }),

  new Evidence({
    id: 'ev-hba1c-microvascular-rct-2018',
    title: 'Intensive glycaemic control and microvascular outcomes in type 2 diabetes: meta-analysis of RCTs',
    abstract: 'Meta-analysis of 7 major RCTs. Intensive HbA1c control (<7%) significantly reduces microvascular complications: retinopathy (22%), nephropathy (20%), neuropathy (14%). Greatest benefit in early diabetes and without established CVD.',
    authors: ['Zoungas S', 'Arima H', 'Gerstein HC', 'Anderson C', 'Woodward M', 'Joshi R'],
    journal: 'The Lancet Diabetes & Endocrinology',
    publicationDate: '2018-09-01',
    doi: '10.1016/S2213-8587(18)30265-7',
    pmid: '30100304',
    source: EvidenceSource.PUBMED,
    language: EvidenceLanguage.EN,
    keywords: ['HbA1c', 'glycemic control', 'microvascular complications', 'retinopathy', 'nephropathy', 'neuropathy', 'diabetes'],
    metadata: { majorTrials: 7 },
  }),

  new Evidence({
    id: 'ev-obesity-interventions-meta-2022',
    title: 'Lifestyle and pharmacological interventions for obesity: comparative effectiveness meta-analysis',
    abstract: 'Network meta-analysis of 112 RCTs (n=52,000). Combined diet + exercise + behaviour modification achieves 5.6 kg weight loss at 12 months. Adding pharmacotherapy (GLP-1 agonists) achieves 11-15 kg. Bariatric surgery superior long-term (25-30 kg).',
    authors: ['Yanovski SZ', 'Yanovski JA'],
    journal: 'JAMA',
    publicationDate: '2022-11-01',
    doi: '10.1001/jama.2022.16828',
    pmid: '36367539',
    source: EvidenceSource.META_ANALYSIS,
    language: EvidenceLanguage.EN,
    keywords: ['obesity', 'obesidade', 'weight loss', 'lifestyle intervention', 'pharmacotherapy', 'IMC', 'GLP-1'],
    metadata: { trialCount: 112, sampleSize: 52000 },
  }),

  new Evidence({
    id: 'ev-crp-cardiac-cohort-2018',
    title: 'High-sensitivity CRP and cardiovascular risk prediction: meta-analysis of prospective studies',
    abstract: 'Meta-analysis of 52 prospective studies (n=160,000). CRP >3 mg/L independently predicts cardiovascular events (HR 1.58) after adjustment for traditional risk factors. Addition of hs-CRP modestly improves risk classification (NRI 0.09).',
    authors: ['Emerging Risk Factors Collaboration', 'Kaptoge S', 'Di Angelantonio E', 'Lowe G'],
    journal: 'The Lancet',
    publicationDate: '2018-03-01',
    doi: '10.1016/S0140-6736(09)60938-0',
    pmid: '20031199',
    source: EvidenceSource.JOURNAL,
    language: EvidenceLanguage.EN,
    keywords: ['CRP', 'PCR', 'high-sensitivity CRP', 'cardiovascular risk', 'inflammation', 'inflamação', 'biomarker'],
    metadata: { prospectiveStudies: 52, sampleSize: 160000 },
  }),

  new Evidence({
    id: 'ev-tsh-metabolic-cohort-2020',
    title: 'Subclinical hypothyroidism and metabolic risk: population-based cohort study',
    abstract: 'Population cohort (n=55,000). Subclinical hypothyroidism (TSH 4.5-10 mIU/L) associated with 17% increased risk of T2DM, 12% increased risk of metabolic syndrome, and weight gain of 1.8 kg over 5 years compared with euthyroid individuals.',
    authors: ['Pearce SH', 'Brabant G', 'Duntas LH', 'Monzani F', 'Peeters RP', 'Razvi S', 'Wemeau JL'],
    journal: 'European Thyroid Journal',
    publicationDate: '2020-08-01',
    doi: '10.1159/000502856',
    pmid: '31602376',
    source: EvidenceSource.JOURNAL,
    language: EvidenceLanguage.EN,
    keywords: ['TSH', 'hypothyroidism', 'hipotireoidismo', 'metabolic syndrome', 'síndrome metabólica', 'thyroid', 'insulin resistance'],
    metadata: { sampleSize: 55000, followupYears: 5 },
  }),
];
